### ISSUE TITLE
Avatary

### ISSUE THREAD

**Issue by xiggeush** [ivall/mikroblog#3]
Proponuję zaimplementować **potężne** avatary.

**Comment by ivall** [comment]
Avatary będą jak polepszę trochę jakościowo kod, dziękuję za propozycję :)

**Comment by ivall** [comment]
Dodałem avatary, aktualnie nie ma możliwości dodawania własnych z kilku powodów:
1. mało miejsca na dysku
2. aktualnie brak żadnego regulaminu itd. przez co użytkownicy mogliby ustawiać avatary niezgodne z prawem
