### ISSUE TITLE
Podgląd polubień.

### ISSUE THREAD

**Issue by xiggeush** [ivall/mikroblog#4]
Proponuję dodać możliwość podglądu dla zarejestrowanych użytkowników, kto polubił wpis.

**Comment by ivall** [comment]
Będzie taka opcja, po najechaniu na ilość lajków będzie się pokazywał tooltip z nickami. Opcja ta będzie też dla niezalogowanych. Dziękuję za propozycję.

**Comment by ivall** [comment]
Dodane.
